### ISSUE TITLE
Add function to perform meta-analysis across sites

### ISSUE THREAD

**Issue by schuemie** [OHDSI/SkeletonComparativeEffectStudy#12]
Likely reuse most of [this code](https://github.com/OHDSI/Legend/blob/master/R/MetaAnalysis.R) from LEGEND.

Also, borrow meta-analysis UI components from the [LEGEND basic viewer](http://data.ohdsi.org/LegendBasicViewer/).

**Comment by ChungsooKim** [comment]
Hi,

I added small functions for generating a forest plot when doing meta-analysis in the current PLE skeleton [here](https://github.com/ABMI/SkeletonComparativeEffectStudy/tree/meta). 
It's based on the EvidenceSynthesis package and I just linked them.

- add codes for creating likelihood_profile.csv in export.R
- add plotMetaAnalysisForest from EvidencySynthesis package to MetaAnalysis.R in SkeletonComparativeEffectStudy package
- fix plotMetaAnalysisForest function for likage with PLE results
- add loadMetaResults function in MetaAnalysis.R
- add those to codeToRun.R

Will it be useful for the community?
