### ISSUE TITLE
Fix data types in NegativeControlOutcomes.sql

### ISSUE THREAD

**Issue by pavgra** [OHDSI/SkeletonComparativeEffectStudy#19]
Update https://github.com/OHDSI/SkeletonComparativeEffectStudy/blob/master/inst/sql/sql_server/NegativeControlOutcomes.sql to reflect fixes from https://github.com/OHDSI/circe-be/pull/89 (issue - https://github.com/OHDSI/circe-be/issues/88).

But, in general, I have a question: why do we even need this file in the repo if it is always overwritten during hydration (by the file generated by circe from JSON)? That only causes confusion in my opinion and requires such kind of synchronization

**Comment by schuemie** [comment]
The original use case for the skeleton was that people would manually modify it for their particular study. The fact that this can now also be done automatically by Hydra is a relatively new development, and doesn't automatically invalidate the original use case.
