### ISSUE TITLE
Table1Specs - is analysisId really covariate_analysis_id?

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/SkeletonComparativeEffectStudy#25]
https://github.com/OHDSI/SkeletonComparativeEffectStudy/blame/master/inst/shiny/EvidenceExplorer/Table1Specs.csv#L1

In the Table1Specs.csv file, the column analysisId seems to have values that correspond to covariate_analysis_id (i.e. the suffix added to concept_id to make it covariate_id).

**Comment by schuemie** [comment]
That is correct.

**Comment by gowthamrao** [comment]
If this is an error, should we rename it in a future version?

**Comment by schuemie** [comment]
No, no error. Why should it be called covariate_analysis_id?
