### ISSUE TITLE
Use package name with function for querySql

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/SkeletonComparativeEffectStudy#44]
https://github.com/OHDSI/SkeletonComparativeEffectStudy/blob/26a209dd7f8362a345697601e03896b33ac1a2e0/inst/shiny/EvidenceExplorer/DataPulls.R#L6

**Comment by schuemie** [comment]
This is dead code. Should be gone when [this](https://github.com/OHDSI/SkeletonComparativeEffectStudy/issues/27) is implemented
