### ISSUE TITLE
R scripts are missing parameter "results_database_schema"

### ISSUE THREAD

**Issue by ssuvorov-fls** [OHDSI/SkeletonComparativeEffectStudy#48]
some scripts ("generateCohort.sql", "cohortCensoredStats.sql") from circe-be use parameter "results_database_schema", so it should be added to R scripts

**Comment by schuemie** [comment]
What does this new argument represent? Does it replace `target_database_schema`? How should users know what value this new argument should take?

**Comment by ssuvorov-fls** [comment]
This argument represents the result schema of the source.
It can have another value ("results") then `target_database_schema `in case when we have daimons with types `temp` and `results.` By default this parameter can have the same value as `target_database_schema`

**Comment by schuemie** [comment]
If I understand correctly, the results_database_schema is to be used when cohort definitions are created with SQL that also generates statistics on the inclusion rules. It requires that certain tables already exist in this schema, or else an error will be thrown. The skeleton does not create these tables, so they already would have to exist., or else the user would get an error. Also, even when the table exists, there's a danger the skeleton would write information to it that would overwrite information that is already there, leading to unexpected behavior.

I recommend generating the cohort SQL without the statements for statistics on the inclusion rules.
