### ISSUE TITLE
Missing includeConceptIds in CohortMethod

### ISSUE THREAD

**Issue by carmenOT** [OHDSI/SkeletonComparativeEffectStudy#49]
[This line](https://github.com/OHDSI/SkeletonComparativeEffectStudy/blame/master/R/CohortMethod.R#L158) is causing the following 
```
Error in strsplit(excludeConceptIds, split = ";") : 
  non-character argument
```
to be replaced with 
``` includeConceptIds <- as.numeric(strsplit(includeConceptIds, split = ";")[[1]]) ```

**Comment by schuemie** [comment]
Thanks! This has already been [fixed](https://github.com/OHDSI/SkeletonComparativeEffectStudy/commit/e19f90f6ef23e28de926d90a6f2ee3f0946d5179) in the `develop` branch. We're currently understaffed, and haven't had time to merge that into master.
