### ISSUE TITLE
getMainResults ordering issue

### ISSUE THREAD

**Issue by jamieweaver** [OHDSI/SkeletonComparativeEffectStudy#6]
The getMainResults function returns a table that is not necessarily ordered by analysisId [here](https://github.com/OHDSI/SkeletonComparativeEffectStudy/blob/master/inst/shiny/EvidenceExplorer/DataPulls.R#L189) but the output$mainTable is ordered [here](https://github.com/OHDSI/SkeletonComparativeEffectStudy/blob/master/inst/shiny/EvidenceExplorer/server.R#L130) . This means when a user selects a row, the diagnostics returned are from the unordered mainResults object. Replacing DataPulls.R line 189

return(cohortMethodResult[idx, ])

with

result <- cohortMethodResult[idx, ]
result <- result[order(result$analysisId), ]
return(result)

worked for my use-case but I haven't tested on other applications yet

**Comment by schuemie** [comment]
I think this was fixed independently [here](https://github.com/OHDSI/SkeletonComparativeEffectStudy/commit/eb8d08d0087ce0da830591519a0130393d98eba1)
