### ISSUE TITLE
Should  the longTermStartDays in createPositiveControlSynthesisArgs be negative?

### ISSUE THREAD

**Issue by chandryou** [OHDSI/SkeletonComparativeEffectStudy#8]
@schuemie , At the line 141 of createPositiveControlSynthesisArgs function in the [createstudyanalysisdetails](https://github.com/OHDSI/SkeletonComparativeEffectStudy/blob/master/extras/CreateStudyAnalysisDetails.R), longTermStartDays  is positive as below

`   covariateSettings = FeatureExtraction::createCovariateSettings(useDemographicsAgeGroup = TRUE,
                                                                   useDemographicsGender = TRUE,
                                                                   useDemographicsIndexYear = TRUE,
                                                                   useDemographicsIndexMonth = TRUE,
                                                                   useConditionGroupEraLongTerm = TRUE,
                                                                   useDrugGroupEraLongTerm = TRUE,
                                                                   useProcedureOccurrenceLongTerm = TRUE,
                                                                   useMeasurementLongTerm = TRUE,
                                                                   useObservationLongTerm = TRUE,
                                                                   useCharlsonIndex = TRUE,
                                                                   useDcsi = TRUE,
                                                                   useChads2Vasc = TRUE,
                                                                   longTermStartDays = 365,
                                                                   endDays = 0) `

Shouldn't this be a negative integer, like -365?

**Comment by schuemie** [comment]
Yikes! Yes, it should. Thanks for catching that!
